language: r
dist: trusty
cache: packages
sudo: required

before_install:
  - sudo apt-get install libgdal1-dev libproj-dev

after_success:
  - Rscript -e 'library(covr);codecov()'

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - r: oldrel
    - r: release
    - r: devel
